const app=document.getElementById('app'),bgm1=document.getElementById('bgm1'),bgm2=document.getElementById('bgm2');let step=0,yesScale=1,wrongCount=0;
const screens=[intro,warmup,funnyPhoto,beboMeter,memoryGame,intrusive,challenge1,sayanQuiz,shopping,mood,couplePuzzle,rapidFire,driveDate,foodFight,compliment,moodRescue,attentionTrap,shoppingTrap,loveTrap,jealousyGame,patienceGame,future,foreverTrap,promise,birthdayBoss,finalChallenge,finalWish];
const funnyWrong=["Eii Megha 😭 eto confidence niye wrong answer? Talent ache boss.","Bebo please 😭 Shilpa sa figure pore hobe, age answer ta thik koro.","Sayan ei answer dekhe officially hurt. Compensation: 2 ta hug mandatory 😌","System confused na, tumi system-ke confused kore diyechho 😭","Abar bhabo madam. Over-excitement-e answer diye dile cholbe na 😂","Wrong answer detected 🚨 Kintu birthday girl bole fine sudhu ekta kiss 😌","Ei option-ta choose korar age intrusive thought permission niyechhile? 😭","Bebo-r confidence: 100. Accuracy: ektu maintenance-e ache 😂"];
function progress(){return `<div class='progress'><i style='width:${Math.round(step/(screens.length-1)*100)}%'></i></div>`}
function card(html){app.innerHTML=`<section class='card'>${step?progress():''}${html}<div id='feedback' class='feedback' aria-live='polite'></div></section>`}
function next(){step++;screens[step]()}
function fadeTrack(track,target,duration=3500){const start=track.volume||0,t=performance.now();function f(n){let p=Math.min(1,(n-t)/duration);track.volume=start+(target-start)*p;if(p<1)requestAnimationFrame(f)}requestAnimationFrame(f)}
function switchToFinalMusic(){fadeTrack(bgm1,0,7000);setTimeout(async()=>{bgm1.pause();bgm2.volume=0;try{await bgm2.play();fadeTrack(bgm2,.34,8000)}catch(e){}},5000)}
function say(msg,type='wrong'){const f=document.getElementById('feedback');if(!f)return;f.className='feedback show '+type;f.innerHTML=msg;clearTimeout(say.t);say.t=setTimeout(()=>f.classList.remove('show'),3200)}
function wrong(msg){say(msg||funnyWrong[wrongCount++%funnyWrong.length])}
function correct(msg,delay=1200){say(msg,'right');setTimeout(next,delay)}
function choice(label,q,opts,correctIndex,rightMsg,wrongMsgs=[]){card(`<span class='pill'>${label}</span><h2>${q}</h2><div class='options'>${opts.map((o,i)=>`<button class='btn ${i===correctIndex?'':'alt'} quiz-option' data-i='${i}'>${o}</button>`).join('')}</div>`);document.querySelectorAll('.quiz-option').forEach(b=>b.onclick=()=>{let i=+b.dataset.i;if(i===correctIndex)correct(rightMsg);else wrong(wrongMsgs[i]||funnyWrong[wrongCount++%funnyWrong.length])})}
function intro(){card(`<span class='pill'>24th July Special 💗</span><h1>Happy Birthday,<br><span class='script'>Megha!</span></h1><p>Ekta chhoto birthday adventure ache tomar jonno… chhoto bolchi, but Sayan banale ektu dramatic toh hobei 😌</p><p class='sub'>25+ levels • Bebo-level chaos • Photos • Mini games • One suspiciously important investigation 👀</p><div class='btns'><button class='btn' id='start'>Start kori? 💕</button></div>`);start.onclick=async()=>{bgm1.volume=0;bgm2.volume=0;try{await bgm1.play();fadeTrack(bgm1,.32,7000)}catch(e){}next()}}
function warmup(){choice('Level 1 — Warm-up','Megha, ready toh? 😏',['Haan, ami ready 😌','Na, ami busy','Age gift dao 😤'],0,'Ei toh birthday girl energy! Cholo shuru kori 💗',['','Busy? Birthday game-er HR leave approve koreni 😭','Gift-er negotiation pore. Age exam dao madam 😌'])}
function funnyPhoto(){choice('Level 2 — Bebo Detector','Identify this international celebrity 🤨',['Obviously ME, Bebo 😌','Kareena Kapoor','Shilpa Shetty'],0,'Correct! Original Bebo 2.0 detected 😂💗',['','Kareena bolche copyright claim korbe 😭','Figure mission under construction madam, answer abar dao 😂']);document.querySelector('h2').insertAdjacentHTML('afterend',`<img class='photo portrait' src='assets/megha_funny.jpg'><p>Clue: “Shilpa sa figure, Bebo si adaa” project-er CEO.</p>`)}
function beboMeter(){choice('Level 3 — Bebo Meter','Bebo energy kobe maximum hoy?',['Shopping cart khola hole 🛍️','Sayan-ke pituni dewar chance pele 😭','Duto-i. Full power mode.'],2,'Certified answer. Bebo battery 200% charged 🔋😂',['Shopping alone na, aro danger ache 👀','Haan but complete syllabus bolo madam 😭',''])}
function memoryGame(){let vals=['🛍️','💗','😤','🍟','🛍️','💗','😤','🍟'].sort(()=>Math.random()-.5),open=[],matched=0;card(`<span class='pill'>Level 4 — Megha Memory Test</span><h2>Pairs match koro 🧠</h2><p>Shopping korar por ki kinechho bhule geleo ekhane memory test hobe 😭</p><div class='memory' id='memory'></div><p id='status' class='sub'>0/4 pairs matched</p>`);vals.forEach(v=>{let b=document.createElement('button');b.className='mem';b.textContent='?';b.onclick=()=>{if(open.length===2||b.dataset.done||open.some(x=>x[0]===b))return;b.textContent=v;open.push([b,v]);if(open.length===2)setTimeout(()=>{if(open[0][1]===open[1][1]){open.forEach(x=>x[0].dataset.done=1);matched++;status.textContent=`${matched}/4 pairs matched`;say(['Nice! Memory ekhono shopping receipt-er cheye better 😌','Oho! Bebo brain activated 🧠✨','Aro ekta! Sayan impressed 👀','Perfect! Memory queen 👑'][matched-1],'right');if(matched===4)setTimeout(next,1300)}else{open.forEach(x=>x[0].textContent='?');wrong(['Eii pair-ta relationship-e compatible na 😭','Na na, eder chemistry nei 😂','Wrong jodi! Abar match-making koro 😌'][Math.floor(Math.random()*3)])}open=[]},600)};memory.appendChild(b)})}
function intrusive(){choice('Level 5 — Intrusive Thought Check','Over-excitement spark hole first ki hote pare?',['Sayan-ke random pituni 😭','Ek sathe 7ta plan','Duto-i, obviously'],2,'Correct! Ei holo certified Megha behaviour 😂',['Pituni ache, but syllabus incomplete 😭','Plans ache, tar sathe collateral damage-o ache 😂',''])}
function challenge1(){card(`<span class='pill'>Level 6 — Real World Challenge</span><h2>10-second Bebo Challenge 💃</h2><div class='challenge'>“Shilpa sa figure,<br>Bebo si adaa”</div><p>Full attitude diye ekbar bolo. Camera na thakleo imaginary paparazzi ache 😌</p><div class='btns'><button class='btn' onclick='correct("Oscar committee call korechhilo. Ami bolechi Bebo busy 😌🏆")'>Done. Oscar kothay? 🏆</button><button class='btn alt' onclick='wrong("Na bolle level unlock hobe na. Bebo contract-er page 24-e lekha ache 😌")'>Ami bolbo na</button></div>`)}
function sayanQuiz(){choice('Level 7 — Sayan Knowledge Test','Sayan-er sathe best combo konta?',['Long drive + food + paglamo 🚗🍟','Silent meditation retreat','Only serious adult discussion'],0,'Exactly. Petrol, food aar nonsense—perfect date 😂💗',['','Amader dujon-ke 10 minute chup korano-i challenge 😭','Adult discussion 7 minute, tarpor abar paglamo 😂'])}
function shopping(){choice('Level 8 — Shopping Investigation','Sayan-er upor rag hole Megha-r secret weapon?',['Calmly journal lekha','Over shopping, tarpor regret 😭','Bank balance-ke respect dewa'],1,'Case solved. Cart full, pore “eta keno kinlam?” episode start 😭😂',['Journal? Bebo-r anger management eto advanced hoyni 😌','','Bank balance ei answer shune nijeyi hese dilo 😭'])}
function mood(){choice('Level 9 — Mood Swing Weather','Megha-r mood forecast kemon?',['Sunny all day ☀️','5 minute-e 4 season 🌦️','Always meditation mode 🧘'],1,'Accurate forecast! Sayan umbrella, food aar hug ready rakhe 😂💗',['Weather department eto optimistic na 😭','','Meditation mode? Ei fake news ke chhoralo? 😂'])}
function couplePuzzle(){let order=[0,1,2,3,4,5,6,7,8].sort(()=>Math.random()-.5);if(order.every((x,i)=>x===i))[order[0],order[1]]=[order[1],order[0]];card(`<span class='pill'>Level 10 — Us Puzzle 💗</span><h2>Amader photo-ta thik koro</h2><p>Duto tile tap kore swap koro. Jemon jhogra-r por amra abar thik hoye jai… photo-tao thik korte hobe 😌</p><div class='grid' id='grid'></div><p class='sub'>Photo detective mode ON 👀</p>`);let sel=null,g=grid;function draw(){g.innerHTML='';order.forEach((n,pos)=>{let d=document.createElement('div');d.className='tile';d.style.backgroundPosition=`${(n%3)*50}% ${Math.floor(n/3)*50}%`;if(sel===pos)d.classList.add('selected');d.onclick=()=>{if(sel===null){sel=pos;draw()}else{[order[sel],order[pos]]=[order[pos],order[sel]];sel=null;draw();if(order.every((x,i)=>x===i)){say('Perfect! Amader photo abar thik hoye gelo 💗','right');setTimeout(next,1600)}}};g.appendChild(d)})}draw()}
function rapidFire(){let qs=[['Rag hole Megha-r favourite cardio?',['Running','Shopping mall walking 🛍️','Yoga'],1],['Over excited Megha-ke handle korar safest equipment?',['Helmet 😭','Calculator','Newspaper'],0],['Bebo mission-er official slogan?',['Eat sleep repeat','Shilpa sa figure, Bebo si adaa','No shopping'],1]],i=0;function ask(){let q=qs[i];choice(`Level 11 — Rapid Fire ${i+1}/3`,q[0],q[1],q[2],['Shopping counts as emotional cardio 😂','Helmet approved by Sayan Safety Board 😭','Mission statement verified. CEO satisfied 😌'][i]);let oldNext=next;document.querySelectorAll('.quiz-option').forEach(b=>{let original=b.onclick;b.onclick=()=>{if(+b.dataset.i===q[2]){say(['Shopping counts as emotional cardio 😂','Helmet approved by Sayan Safety Board 😭','Mission statement verified. CEO satisfied 😌'][i],'right');setTimeout(()=>{i++;if(i<qs.length)ask();else{step++;screens[step]()}},1000)}else wrong()}})}ask()}
function driveDate(){choice('Level 12 — Perfect Date Builder','Ekta perfect Sayan-Megha date-e ki mandatory?',['Food 🍔','Long drive 🚗','Duto-i + random jhogra bonus 😭'],2,'Correct. Romance-er sathe complimentary chaos 😂💗',['Food ache but gari kothay? 👀','Drive ache but khide pele revolution hobe 😭',''])}
function foodFight(){choice('Level 13 — Serious Relationship Question','Last bite ta kar?',['Megha-r, obviously 😌','Sayan-er','Je age tule nibe tar 😈'],0,'Correct. Relationship peace treaty successfully signed 😂💗',['','Ei answer-e relationship court bosbe 😭','Risky behaviour detected. Fork war incoming 🍴😂'])}
function compliment(){card(`<span class='pill'>Level 14 — Compliment Machine</span><h2>Sayan-er theke ekta compliment choose koro 💗</h2><p>Warning: shob guloi true, tai wrong answer nei 😌</p><div class='options'><button class='btn alt quiz-option'>Tomar smile-ta amar favourite 💗</button><button class='btn alt quiz-option'>Tomar paglamo chara amar din boring 😭😂</button><button class='btn alt quiz-option'>Tumi amar nijer manush, bas 😌</button></div>`);document.querySelectorAll('.quiz-option').forEach((b,i)=>b.onclick=()=>correct(['Ei smile-ta preserve kore rakhbe, please 💗','Haan, pituni part-ta optional rakhte paro though 😭','Ei answer-ta simple, but amar kache shobcheye true 😌💗'][i],1500))}
function moodRescue(){choice('Level 15 — Emergency Bebo Protocol','Megha upset. Sayan-er best rescue plan?',['“Calm down” bola 😬','Food + hug + shona 💗','Phone kere newa'],1,'Correct protocol! Food first, logic later 😌💗',['“Calm down” bole keu konodin calm hoyeche? Sayan bachte chai 😭','','Phone nile shopping thambe, but Sayan-o bachbe na 😂'])}

function attentionTrap(){card(`<span class='pill'>Level 16 — Attention Test 👀</span><h2>Sayan jodi bole “amar kotha shono”, Megha ki korbe?</h2><div class='options'><button class='btn' id='listen'>Haan shunchi 😌</button><button class='btn alt dodge' id='later'>Pore shunbo 😏</button><button class='btn alt dodge' id='phone'>Age phone-ta dekhi 📱</button></div><p id='trapmsg' class='tease'>Correct answer nijeyi tomake khুঁজছে 👀</p>`);let good=listen,bads=[later,phone],msgs=['Pore mane kon year, madam? 😭','Phone-ke eto attention, Sayan protest korche 😂','Bebo multitasking department temporarily closed 😌','Ei option-ta abar choose korle Sayan dramatic sigh debe 😭'];bads.forEach(b=>b.onclick=()=>{trapmsg.textContent=msgs[wrongCount++%msgs.length];good.style.transform=`scale(${Math.min(1.8,1.08+(wrongCount%6)*.12)})`;b.style.transform=`translateX(${(Math.random()>.5?1:-1)*(30+Math.random()*80)}px)`});good.onclick=()=>correct('Ei toh! Sayan-er kotha occasionally shona healthy habit 😂💗',1400)}
function shoppingTrap(){let clicks=0;card(`<span class='pill'>Level 17 — Cart Control Challenge 🛍️</span><h2>Rag kore shopping cart-e 9ta jinis add hoye geche. Ki korbe?</h2><div class='options'><button class='btn alt' id='buy'>BUY ALL 😈</button><button class='btn' id='think'>3 second bhabbo 😌</button></div><p id='shopmsg' class='tease'>Wallet quietly praying… 🙏</p>`);buy.onclick=()=>{clicks++;let m=['Bank balance faint kore gelo 😭','Courier dada bolche abar Megha madam? 😂','Regret episode loading: 67%…','Sayan calculator niye boshe geche 😭😂'];shopmsg.textContent=m[(clicks-1)%m.length];think.style.transform=`scale(${1+Math.min(.7,clicks*.14)})`};think.onclick=()=>correct('Historic moment! Bebo cart-er age bhabche! National holiday declare koro 😂🏆',1500)}
function jealousyGame(){choice('Level 19 — Sayan Complaint Department','Sayan jodi bole “tumi amar kotha shono na”, Megha-r best reply?',['Haan baba, bolo ki bolchhile 😌','Ami shob shuni! ...ki bolchhile? 😭','Shopping app open kora'],0,'Rare footage: Megha calmly listening 😂💗',['','Second half-e nijeyi case prove kore dile 😭','Complaint theke cart-e ki kore chole gele madam? 😂'])}
function patienceGame(){card(`<span class='pill'>Level 20 — Patience Meter</span><h2>5 second kono button na tipe wait korte parbe? 😏</h2><p id='waitmsg' class='challenge'>5</p><button class='btn alt' id='tempt'>TIPBO 😈</button>`);let n=5,t=setInterval(()=>{n--;if(n>0)waitmsg.textContent=n;else{clearInterval(t);waitmsg.textContent='PASS! 🎉';setTimeout(()=>correct('Oho! Intrusive thought control unlocked 😌🏆',1200),300)}},1000);tempt.onclick=()=>{n=5;waitmsg.textContent='Abar 5 😭';wrong(['Bolechhilam na tipbe na! Bebo fingers independent naki? 😭','Intrusive thought: 1, Patience: 0 😂','Abar countdown reset. Ei button tomar enemy 😌'][wrongCount%3])}}
function foreverTrap(){card(`<span class='pill'>Level 22 — Contract Renewal 💗</span><h2>Sayan-er sathe aro onek birthday celebrate korbe?</h2><div class='runzone' id='zone2'><div class='yesAnchor'><button class='btn' id='foreverYes'>Obviously HAAN 💗</button></div><button class='btn alt noRun' id='maybeBtn'>Maybe 😏</button></div><p id='forevermsg' class='tease'>“Maybe” department suspiciously unstable 👀</p>`);let m=maybeBtn,z=zone2,y=foreverYes,c=0;function escapeMaybe(){let r=z.getBoundingClientRect(),b=m.getBoundingClientRect();m.style.left=Math.random()*Math.max(20,r.width-b.width-12)+'px';m.style.top=Math.random()*Math.max(20,r.height-b.height-12)+'px';m.style.transform='none';c++;y.style.transform=`scale(${Math.min(2.1,1+c*.13)})`;forevermsg.textContent=['Maybe ki? Calendar already booked 😌','Universe bolche answer-ta clear koro 😂','Sayan renewal form niye dariye ache 😭💗','Ei button-o commitment issue-e bhugche 😂'][c%4]}m.onmouseenter=escapeMaybe;m.ontouchstart=e=>{e.preventDefault();escapeMaybe()};m.onclick=e=>{e.preventDefault();escapeMaybe()};y.onclick=()=>correct('Lifetime birthday chaos package renewed 💗😂',1500)}
function birthdayBoss(){choice('Level 24 — Birthday Boss Battle 🎂','Aaj birthday girl-er official power ki?',['Unlimited attitude 😌','Unlimited cake 🍰','Duto-i + Sayan-ke order dewa 😭'],2,'Boss battle impossible chhilo. Birthday Bebo wins 😂👑',['Attitude ache, cake miss korle crime 😭','Cake ache, Bebo authority-o ache 😌',''])}

function loveTrap(){card(`<span class='pill'>SPECIAL LEVEL — Most Important Question</span><h2>Megha, tumi ki Sayan-ke bhalobasho? 👀</h2><p class='sub'>System bolche carefully choose korte. System suspiciously biased 😌</p><div class='runzone' id='zone'><div class='yesAnchor'><button class='btn' id='yesBtn'>HAAN 💗</button></div><button class='btn alt noRun' id='noBtn'>NA 😏</button></div><p id='tease' class='tease'>Choose wisely… 👀</p>`);let no=noBtn,zone=document.getElementById('zone'),yes=yesBtn,teases=['Na button-tao tomake trust korche na 😭','Haan ta boro hocche… universe-er sign 😌','Abar NA? Sayan sad acting start korbe 😭','Bujhe jao Megha, destiny clear 💗','NA dhorte gele cardio hoye jabe 😂','System: “Madam please cooperate” 😭'];function run(){let z=zone.getBoundingClientRect(),b=no.getBoundingClientRect(),x=Math.random()*Math.max(20,z.width-b.width-12),y=Math.random()*Math.max(20,z.height-b.height-12);no.style.left=x+'px';no.style.top=y+'px';no.style.transform='none';yesScale=Math.min(2.5,yesScale+.16);yes.style.transform=`scale(${yesScale})`;tease.textContent=teases[wrongCount++%teases.length]}no.onmouseenter=run;no.ontouchstart=e=>{e.preventDefault();run()};no.onclick=e=>{e.preventDefault();run()};yes.onclick=()=>correct('Ei toh! System already janto 😌💗',1500)}
function future(){choice('Level 17 — Future Forecast','Aro onek birthday, drive, food date, jhogra aar patch-up eksathe korbo toh?',['Haan, obviously 💗','Dekha jabe 😏','Na'],0,'Best answer. Contract auto-renewed for lifetime 😌💗',['','“Dekha jabe” accepted na. Terms & conditions-e HAAN required 😭','System bolche typo hoyeche. Abar try koro 😌'])}
function promise(){choice('Level 18 — Tiny Promise','Ekta promise choose koro 😌',['Rag holeo eventually kotha bolbo 💗','Shopping-er age 3 second bhabbo 😭','Sayan-ke pituni ektu gentle korbo 😂'],0,'Eta-i shobcheye important. Jhogra hobe, but amra kotha bolbo 💗',['','3 second diye Amazon cart bachbe na 😭','Gentle pituni-o pituni, madam 😂'])}
function finalChallenge(){card(`<span class='pill'>Level 19 — Birthday Challenge</span><h2>Final unlock ritual 🎂</h2><p>Ekta boro smile dao, nijeke bolo <b>“Ami Bebo, aaj amar birthday, aaj amar shob maaf”</b> 😌😂</p><div class='btns'><button class='btn' onclick='correct("Birthday wish vault unlocked! 💗",1400)'>Done 😌✨</button><button class='btn alt' onclick='wrong("Na na, smile verification camera imaginary holeo strict 😭😂")'>Ami korini 😏</button></div>`)}
function confetti(){for(let i=0;i<90;i++){let e=document.createElement('div');e.className='confetti';e.textContent=['💗','✨','🌸','💕'][i%4];e.style.left=Math.random()*100+'vw';e.style.animationDelay=Math.random()*2+'s';e.style.fontSize=12+Math.random()*22+'px';document.body.appendChild(e)}}
function finalWish(){switchToFinalMusic();confetti();card(`<div class='final'><span class='pill'>For my Bubu 💗</span><h1 class='script'>Happy Birthday, Bubu</h1><p>Bubu,

Happy Birthday amar pagli. 💗

Ami jani ami sob shomoy perfectly express korte pari na je tumi amar jonno exactly koto ta important. Majhe majhe amader jhogra hoy, tumi rag koro, mood swing hoy, over excited hoye ek sathe doshta jinis kore felo, aar majhe majhe oi excitement-e amar upor free-te WWE practice-o hoy 😭😂. Kintu ei shob kichu miliyei tumi amar Megha, amar Bubu.

Tomar oi sudden excitement, tomar random plans, tomar rag kore shopping kora aar tarpor nijer purchase dekhe regret kora—shob kichu amar life-er ekta part hoye geche. Aar sotti bolte, ami chai ei paglamo gulo kokhono completely change na hok. Haan, shopping-ta ektu kom hole amar wallet khushi hobe… but baki tumi exactly tumi-i theko. 😌

Ami chai tomar life-e tumi onek happy thako, nijer shob dream fulfill koro, nijeke niye proud feel koro, aar haan—tomar legendary “Shilpa sa figure, Bebo si adaa” mission-o ekdin complete hok 😂💗. But amar kache tumi kono future version-er jonno special na. Tumi ekhon je rokom, oi rokom-i amar khub nijer.

Thank you amar life-e thakar jonno, amar nonsense tolerate korar jonno, amar sathe hashar jonno, amar sathe jhogra kore abar amar kachhei fire ashar jonno. Ami chai amader aro onek drives hok, onek khawa-dawa hok, onek stupid joke hok, kichu jhogra-o hok—kintu prottekbar seshe amra dujon abar eki team-e thaki.

Aaj tomar din. Tai aajke mon khule hasho, over excited hao, ja ichhe koro… aaj pituni-o limited edition birthday offer dhore nilam 😭💗.

Happy Birthday, amar Bubu. Tumi bhalo theko, khushi theko, aar amar sathe ei rokom paglamo korte thako. Ami tomake khub bhalobashi. Maybe sob shomoy thik bhabe bolte pari na, but I hope amar care-ta tumi prottekdin feel koro.

— Tomar Sayan 💗</p><div class='btns'><button class='btn' onclick='fadeTrack(bgm2,0,5000);setTimeout(()=>location.reload(),4800)'>Abar khelbo? 🥹</button></div></div>`) }
for(let i=0;i<22;i++){let h=document.createElement('span');h.className='heart';h.textContent='♥';h.style.left=Math.random()*100+'%';h.style.animationDuration=8+Math.random()*10+'s';h.style.animationDelay=-Math.random()*12+'s';hearts.appendChild(h)}intro();
